---
title: "hw2_solution"
author: "Eric Scott"
date: "1/22/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Probability for two models

```{r}
p <- c("fair" = 0.5, "weighted" = 0.55)
k <- 110
N <- 200

binProb <- dbinom(k, N, p)
binProb
```

# 2 Calculate posteriors with flat priors

```{r}
priors <- c(0.5, 0.5)
pdata <- sum(binProb * priors)
pmodels <- binProb * priors / pdata
pmodels
```

# 3 Likelihood ratio

```{r}
binProb[2] / binProb[1]
```

Model 2 is about 2.7x more likely than model 1

# 4 What would Nate's prior need to be to make model 1 more likely?

Nate believes the P(heads) = 0.5

set Nate's prior belief to x

P(model1) = x

P(model2) = 1-x because we are assuming there are only 2 possible models

P(data|model1) = 0.02079869

P(data) = 0.02079869x + 0.05663140(1-x)

0.5 = 0.02079869x/(0.02079869x + 0.05663140(1-x))  
0.5 = 0.02079869x/(0.02079869x + 0.05663140 - 0.05663140x)  
0.5 = 0.02079869x/(0.02079869x + 0.05663140 - 0.05663140x)  
0.5 = 0.02079869x/0.05663140 - 0.03583271x  
0.5(0.05663140 - 0.03583271x) = 0.02079869x  
0.0283157 - 0.01791635x = 0.02079869x  
0.0283157 = 0.03871504x  
x = 0.7313876


