---
title: "Welcome to Ecological Statistics and Data!"
author: "Eric Scott"
date:  "2019-01-16"
output:
  powerpoint_presentation:
    reference_doc: template.pptx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Overview

- 20th century: design experiments to fit statistical analysis assumptions  
- 21st century: option to design statistical models to be more like data  
   + Focus on linear models and their extensions

## Why "Ecological" statistics?

- Ecologists often count things and watch when they reproduce and die
- These types of data have special properties
- Violate assumptions of statistical tests typically covered in more general or introductory courses

## Introductions

The team:  

- Eric Scott (eric.scott@tufts.edu)
- Avalon Owens (avalon.owens@tufts.edu)

The class:   

- Undergraduate and graduate students from several departments with varied backgrounds in math, statistics, computer programming, and ecology.

## Today's Outline

1. Logistics
2. Probability
3. Homework

## Logistics

Take a look at the syllabus:

- General format (lectures mixed with computer exercises – find a partner or 2)
- Books: 	Bolker, R4DS
- Syllabus
- Access to laptops
- Lab

## Probability: textbook definition

"If an observation is made $N$ times and event $A$ occurs $N_A$ times, then with a high degree of **certainty**, the relative frequency of $N_A/N$ is **close** to $P(A)$, the probability of $A$ in a single trial, $P(A) \approx N_A/N$, provided $N$ is **sufficiently large**."


Mathematical restatement:   

$$
P(A) = \lim_{N\to\infty} \left(\frac{N_A}{N}\right)
$$


## Example application  

Common ecological application: survival and reproduction of perennial wildflowers  
Useful to know to understand and predict what will happen to populations over time  

- Mark individual plants and watch their performance over time.   
-	What is the probability that a plant will survive from one year to the next?  
-	What is the probability that a plant that survives will flower?  

## Example application

FOR A PARTICULAR DATA SET, we can use the definition of probability to estimate these probabilities (“provided N is **sufficiently large**”)

Say we have 5 plants, 4 live, and 1 of these flower  

|Plant # | fate|
|-------:|---:|
|1 | Flowers|
|2 | Vegetative|
|3 | Vegetative|
|4 | Vegetative|
|5 | Dead|


$N$ = total # trials
$N_A$ = number of times $A$ occurs

Survival:  

- What is $N$?
- What is $N_A$?
- What is $P(A)$?


Flowering, for plants that survive:  

- What is $N$?
- What is $N_A$?
- What is $P(A)$?

**FOR THOUGHT:** Based on these data, what is the probability that a plant survives AND flowers?

## Sampling and Scope of Inference

Definition of probability assumes trials are representative of a “population”

"population" (statistics definition) = larger group for which you estimating the probability

Trials should be **representative** and **independent**.  
- Sampling types:
    + Random
		+ Stratified (e.g. randomly selected transects)
		+ Systematic (e.g. every 10 paces along transect)
		+ Haphazard
- Scope of inference = “population” over which your data are a **representative** and **independent** observations

## Homework

Measure a probability of some event by sampling a population.

